# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaction.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class AnotherWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("TransactionWindow")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.resize(401, 488)
        self.setStyleSheet("background-color: white;")
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 443))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.transactionIDLabel_06 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_06.setObjectName("transactionIDLabel_06")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_06)
        self.transactionIDLabel_19 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_19.setText("")
        self.transactionIDLabel_19.setObjectName("transactionIDLabel_19")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_19)
        self.transactionIDLabel_20 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_20.setText("")
        self.transactionIDLabel_20.setObjectName("transactionIDLabel_20")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_20)
        self.transactionIDLabel_07 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_07.setObjectName("transactionIDLabel_07")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_07)
        self.transactionIDLabel_08 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_08.setObjectName("transactionIDLabel_08")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_08)
        self.transactionIDLabel_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_21.setText("")
        self.transactionIDLabel_21.setObjectName("transactionIDLabel_21")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_21)
        self.transactionIDLabel_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_10.setObjectName("transactionIDLabel_10")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_10)
        self.transactionIDLabel_23 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_23.setText("")
        self.transactionIDLabel_23.setObjectName("transactionIDLabel_23")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_23)
        self.transactionIDLabel_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_11.setObjectName("transactionIDLabel_11")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_11)
        self.transactionIDLabel_24 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_24.setText("")
        self.transactionIDLabel_24.setObjectName("transactionIDLabel_24")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_24)
        self.transactionIDLabel_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_12.setObjectName("transactionIDLabel_12")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_12)
        self.transactionIDLabel_25 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_25.setText("")
        self.transactionIDLabel_25.setObjectName("transactionIDLabel_25")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_25)
        self.transactionIDLabel_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_13.setObjectName("transactionIDLabel_13")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_13)
        self.transactionIDLabel_26 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_26.setText("")
        self.transactionIDLabel_26.setObjectName("transactionIDLabel_26")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_26)
        self.transactionIDLabel_01 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_01.setObjectName("transactionIDLabel_01")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_01)
        self.transactionIDLabel_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_14.setText("")
        self.transactionIDLabel_14.setObjectName("transactionIDLabel_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_14)
        self.transactionIDLabel_02 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_02.setObjectName("transactionIDLabel_02")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_02)
        self.transactionIDLabel_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_15.setText("")
        self.transactionIDLabel_15.setObjectName("transactionIDLabel_15")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_15)
        self.transactionIDLabel_03 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_03.setObjectName("transactionIDLabel_03")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_03)
        self.transactionIDLabel_04 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_04.setObjectName("transactionIDLabel_04")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_04)
        self.transactionIDLabel_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_16.setText("")
        self.transactionIDLabel_16.setObjectName("transactionIDLabel_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_16)
        self.transactionIDLabel_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_17.setText("")
        self.transactionIDLabel_17.setObjectName("transactionIDLabel_17")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_17)
        self.transactionIDLabel_05 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_05.setObjectName("transactionIDLabel_05")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_05)
        self.transactionIDLabel_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_18.setText("")
        self.transactionIDLabel_18.setObjectName("transactionIDLabel_18")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_18)
        self.transactionIDLabel_09 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_09.setObjectName("transactionIDLabel_09")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_09)
        self.transactionIDLabel_22 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_22.setText("")
        self.transactionIDLabel_22.setObjectName("transactionIDLabel_22")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_22)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.line)
        self.line_2 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.line_3 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_3)
        self.line_4 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_4)
        self.line_5 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line_5)
        self.line_6 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.line_6)
        self.line_7 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.line_7)
        self.line_8 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.line_8)
        self.line_9 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.line_9)
        self.line_10 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.line_10)
        self.line_11 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.line_11)
        self.line_12 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.line_12)
        self.line_13 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.line_13)
        self.line_15 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.line_15)
        self.line_16 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.line_16)
        self.line_17 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.line_17)
        self.line_18 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.line_18)
        self.line_19 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.line_19)
        self.line_20 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.line_20)
        self.line_22 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.line_22)
        self.line_23 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_23)
        self.transactionIDLabel_27 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_27.setText("")
        self.transactionIDLabel_27.setObjectName("transactionIDLabel_27")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.transactionIDLabel_27)
        self.transactionIDLabel_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.transactionIDLabel_4.setObjectName("transactionIDLabel_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.transactionIDLabel_4)
        self.line_14 = QtWidgets.QFrame(self)
        self.line_14.setGeometry(QtCore.QRect(290, 400, 0, 3))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_21 = QtWidgets.QFrame(self)
        self.line_21.setGeometry(QtCore.QRect(150, 450, 0, 3))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        self.transactionIDLabel_06.setText(_translate("Form", "Transaction ID"))
        self.transactionIDLabel_07.setText(_translate("Form", "Status"))
        self.transactionIDLabel_08.setText(_translate("Form", "Transaction date"))
        self.transactionIDLabel_10.setText(_translate("Form", "From:"))
        self.transactionIDLabel_11.setText(_translate("Form", "To:"))
        self.transactionIDLabel_12.setText(_translate("Form", "Total cost"))
        self.transactionIDLabel_13.setText(_translate("Form", "Fee"))
        self.transactionIDLabel_01.setText(_translate("Form", "First name"))
        self.transactionIDLabel_02.setText(_translate("Form", "Last name"))
        self.transactionIDLabel_03.setText(_translate("Form", "e-mail"))
        self.transactionIDLabel_04.setText(_translate("Form", "Type of cofee"))
        self.transactionIDLabel_05.setText(_translate("Form", "Number"))
        self.transactionIDLabel_09.setText(_translate("Form", "Delivery date"))
        self.transactionIDLabel_4.setText(_translate("Form", "Address"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())

